name: context-timer
base: core22
version: '0.1.0'
summary: Track multiple concurrent task timers and context switches
description: |
  Context Timer is a desktop application for tracking multiple concurrent 
  task timers, measuring time spent on tasks, and counting context switches 
  during work sessions.
  
  Features:
  - Multiple concurrent timers running simultaneously
  - Automatic context switch tracking
  - Task management with custom colors
  - Daily and weekly reports
  - CSV export for data analysis
  - Work Day timer with Lunch and Break tracking
  - Persistent state across app restarts

icon: snap/gui/icon.svg

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  context-timer:
    command: bin/context-timer
    extensions: [gnome]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
    environment:
      PYTHONPATH: $SNAP/lib/python3.10/site-packages:$PYTHONPATH

parts:
  context-timer:
    plugin: python
    source: .
    python-packages:
      - PyQt6>=6.4.0
    stage-packages:
      - libqt6core6
      - libqt6gui6
      - libqt6widgets6
      - libqt6dbus6
      - qt6-qpa-plugins
      - libxkbcommon0
      - libgl1
      - libglu1-mesa
      - libxcb-xinerama0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-shape0
    build-packages:
      - python3-dev
      - python3-pip
    override-build: |
      craftctl default
      # Ensure the entry point is executable
      chmod +x $CRAFT_PART_INSTALL/bin/context-timer

layout:
  /usr/share/qt6:
    symlink: $SNAP/usr/share/qt6
